# Generated by Django 5.0.1 on 2024-01-30 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='somebody', max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, default=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actor/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default_ctg', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default_show', max_length=100)),
                ('description', models.TextField(blank=True, default='default_description', max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='show/')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('type', models.CharField(blank=True, choices=[('Movie', 'Movie'), ('Series', 'Series'), ('Theater', 'Theater'), ('Animation', 'Animation')], max_length=50)),
                ('category', models.ForeignKey(default='default_ctg', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_show', to='movies.category')),
                ('main_actor', models.ForeignKey(default='somebody', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='mainActor_show', to='movies.actor')),
                ('sub_actor', models.ForeignKey(default='somebody2', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subActor_show', to='movies.actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_show', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
